### ISSUE TITLE
Some applications are failing to open files from file manager.

### ISSUE THREAD

**Issue by mmtrt** [snapcrafters/sommelier-core#20]
So some of my `sommelier-core` ported snaps are failing to open files previously worked just fine.

Failing snaps
`acrordrdc`
`foobar2000` see user [issue](https://forum.snapcraft.io/t/cant-open-files-with-foobar2000/26463) though desktop actions do work which do args like `/play`.
`irfranview`
`notepad3`

Working snaps
`notepad-plus-plus`
`resourcehacker`

I think this need unix path conversion for file arguments.

See my old f2k [changes](https://github.com/mmtrt/foobar2000/blob/787347b82145a96aca60b81455222e80006a00eb/snap/local/src/foobar2000#L351)

**Comment by merlijn-sebrechts** [comment]
I was hoping we didn't need this since the old code assumes every argument which isn't a flag is a path. Plus, it requires users to use unix-style flags instead of windows-style flags. Are there no better options?

* I think we could probably solve the file manager issue by [including "Z:" in the `.desktop` file](https://bugs.launchpad.net/ubuntu/+source/wine/+bug/243390/comments/22). Something like this: `myapp "Z:"$@`. That wouldn't fix CLI invocations, however.
* [This comments claims it's fixed](https://bugs.launchpad.net/ubuntu/+source/wine/+bug/243390/comments/25) but this requires to use `start.exe`? Or does it just cause Wine to generate correct `.desktop` files?

How do apps like PlayOnLinux fix stuff like this? Or is it also broken if you install the app with PlayOnLinux?

**Comment by mmtrt** [comment]
I've fixed issue without needing to use `start /unix` in MR so I'm checking if action arg is a valid file then proceed adding `z:` to it.

Though not tested apps that use flag like args having `-add` `-play` but they should work since I'm checking if arg is file else it will proceeds as usuall.
